# Generated by Django 4.2 on 2023-04-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_answer_id_alter_question_id_alter_report_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='data_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='popularity',
            field=models.FloatField(),
        ),
    ]
